
version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NODE_ENV=production
    depends_on:
      - postgres17
    restart: unless-stopped

  postgres17:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-muebleria_db}
      - POSTGRES_USER=${POSTGRES_USER:-muebleria_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secure_password_123}
    ports:
      - "5432:5432"
    volumes:
      - postgres17_data:/var/lib/postgresql/data
    restart: unless-stopped
    command: >
      postgres 
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1

volumes:
  postgres17_data:

